// Code generated by protoc-gen-go. DO NOT EDIT.
// source: miniblog/v1/miniblog.proto

package v1 // import "github.com/qiwen698/miniblog/pkg/proto/miniblog/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamppb "google.golang.org/protobuf/types/known/timestamppb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserInfo struct {
	Username             string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Nickname             string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email                string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	PostCount            int64                  `protobuf:"varint,5,opt,name=postCount,proto3" json:"postCount,omitempty"`
	CreateAt             *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpdateAt             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_miniblog_29a64459bdc6c0ab, []int{0}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (dst *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(dst, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserInfo) GetPostCount() int64 {
	if m != nil {
		return m.PostCount
	}
	return 0
}

func (m *UserInfo) GetCreateAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreateAt
	}
	return nil
}

func (m *UserInfo) GetUpdateAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdateAt
	}
	return nil
}

// ListUserRequest 制定了 `ListUser` 接口的请求参数.
type ListUserRequest struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserRequest) Reset()         { *m = ListUserRequest{} }
func (m *ListUserRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserRequest) ProtoMessage()    {}
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_miniblog_29a64459bdc6c0ab, []int{1}
}
func (m *ListUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserRequest.Unmarshal(m, b)
}
func (m *ListUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserRequest.Marshal(b, m, deterministic)
}
func (dst *ListUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserRequest.Merge(dst, src)
}
func (m *ListUserRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserRequest.Size(m)
}
func (m *ListUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserRequest proto.InternalMessageInfo

func (m *ListUserRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListUserRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

// ListUserResponse 指定了 `GET /v1/users `接口的返回参数，相当于 HTTP Response
type ListUserResponse struct {
	TotalCount           int64       `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Users                []*UserInfo `protobuf:"bytes,2,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListUserResponse) Reset()         { *m = ListUserResponse{} }
func (m *ListUserResponse) String() string { return proto.CompactTextString(m) }
func (*ListUserResponse) ProtoMessage()    {}
func (*ListUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_miniblog_29a64459bdc6c0ab, []int{2}
}
func (m *ListUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserResponse.Unmarshal(m, b)
}
func (m *ListUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserResponse.Marshal(b, m, deterministic)
}
func (dst *ListUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserResponse.Merge(dst, src)
}
func (m *ListUserResponse) XXX_Size() int {
	return xxx_messageInfo_ListUserResponse.Size(m)
}
func (m *ListUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserResponse proto.InternalMessageInfo

func (m *ListUserResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListUserResponse) GetUsers() []*UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "v1.UserInfo")
	proto.RegisterType((*ListUserRequest)(nil), "v1.ListUserRequest")
	proto.RegisterType((*ListUserResponse)(nil), "v1.ListUserResponse")
}

func init() {
	proto.RegisterFile("miniblog/v1/miniblog.proto", fileDescriptor_miniblog_29a64459bdc6c0ab)
}

var fileDescriptor_miniblog_29a64459bdc6c0ab = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcf, 0x4f, 0xab, 0x40,
	0x10, 0x7e, 0x94, 0xd7, 0x4a, 0xb7, 0x26, 0x9a, 0xb5, 0x31, 0x84, 0x18, 0x25, 0x9c, 0x38, 0x41,
	0x8a, 0xa6, 0xea, 0xc9, 0xd8, 0x9e, 0x4c, 0xf4, 0x42, 0xd4, 0x83, 0x37, 0xa8, 0x0b, 0xdd, 0x14,
	0x76, 0x28, 0x3b, 0xd4, 0x7f, 0xde, 0x83, 0x81, 0x75, 0xdb, 0xea, 0xc5, 0x1b, 0xdf, 0x8f, 0x19,
	0xe6, 0x9b, 0x1d, 0xe2, 0x94, 0x5c, 0xf0, 0xb4, 0x80, 0x3c, 0xdc, 0x4c, 0x42, 0xfd, 0x1d, 0x54,
	0x35, 0x20, 0xd0, 0xde, 0x66, 0xe2, 0x5c, 0xe4, 0x00, 0x79, 0xc1, 0xc2, 0x8e, 0x49, 0x9b, 0x2c,
	0x44, 0x5e, 0x32, 0x89, 0x49, 0x59, 0x29, 0x93, 0xf7, 0x69, 0x10, 0xeb, 0x45, 0xb2, 0xfa, 0x41,
	0x64, 0x40, 0x1d, 0x62, 0x35, 0x92, 0xd5, 0x22, 0x29, 0x99, 0x6d, 0xb8, 0x86, 0x3f, 0x8c, 0xb7,
	0xb8, 0xd5, 0x04, 0x5f, 0xac, 0x3a, 0xad, 0xa7, 0x34, 0x8d, 0xe9, 0x98, 0xf4, 0x59, 0x99, 0xf0,
	0xc2, 0x36, 0x3b, 0x41, 0x81, 0x96, 0xad, 0x96, 0x20, 0x98, 0xfd, 0x5f, 0xb1, 0x1d, 0xa0, 0x67,
	0x64, 0x58, 0x81, 0xc4, 0x39, 0x34, 0x02, 0xed, 0xbe, 0x6b, 0xf8, 0x66, 0xbc, 0x23, 0xe8, 0x94,
	0x58, 0x8b, 0x9a, 0x25, 0xc8, 0xee, 0xd1, 0x1e, 0xb8, 0x86, 0x3f, 0x8a, 0x9c, 0x40, 0x45, 0x08,
	0x74, 0x84, 0xe0, 0x59, 0x47, 0x88, 0xb7, 0xde, 0xb6, 0xae, 0xa9, 0xde, 0x55, 0xdd, 0xc1, 0xdf,
	0x75, 0xda, 0xeb, 0xdd, 0x91, 0xa3, 0x47, 0x2e, 0xb1, 0xdd, 0x40, 0xcc, 0xd6, 0x0d, 0x93, 0xd8,
	0x8e, 0x5d, 0xf0, 0x92, 0x63, 0xb7, 0x01, 0x33, 0x56, 0x80, 0x9e, 0x92, 0x01, 0x64, 0x99, 0x64,
	0xd8, 0x85, 0x37, 0xe3, 0x6f, 0xe4, 0xbd, 0x92, 0xe3, 0x5d, 0x03, 0x59, 0x81, 0x90, 0x8c, 0x9e,
	0x13, 0x82, 0x80, 0x49, 0xa1, 0x32, 0xaa, 0x36, 0x7b, 0x0c, 0xf5, 0x48, 0xbf, 0xf5, 0x4b, 0xbb,
	0xe7, 0x9a, 0xfe, 0x28, 0x3a, 0x0c, 0x36, 0x93, 0x40, 0xbf, 0x41, 0xac, 0xa4, 0x68, 0x4e, 0xac,
	0x27, 0x2e, 0xf8, 0xac, 0x80, 0x9c, 0x5e, 0x13, 0x4b, 0xff, 0x83, 0x9e, 0xb4, 0xe6, 0x5f, 0x23,
	0x3b, 0xe3, 0x9f, 0xa4, 0x1a, 0xc3, 0xfb, 0x37, 0xbb, 0x7a, 0x8b, 0x72, 0x8e, 0xcb, 0x26, 0x0d,
	0x16, 0x50, 0x86, 0x6b, 0xfe, 0xc1, 0xc4, 0xf4, 0xf6, 0x66, 0x7b, 0x27, 0x61, 0xb5, 0xca, 0xd5,
	0x65, 0x84, 0x7b, 0x67, 0x94, 0x0e, 0x3a, 0xea, 0xf2, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x32, 0x3d,
	0x55, 0xea, 0x5c, 0x02, 0x00, 0x00,
}
